import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Shafinur || Rahman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
     <Navbar/>
     
    </div>
  )
}
