import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Shafinur || Rahman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <h1 className="text-4xl font-bold underline">
      Hello world!
    </h1>
     
    </div>
  )
}
